apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /registry
    server: <SERVER_NAME_OR_IP>
  persistentVolumeReclaimPolicy: Retain
